### ISSUE TITLE
[BUG] [Retail] overshields (with Overshields Addon) dont show on player/target frame

### ISSUE THREAD

**Issue by fanhubx** [Syiana/SUI#43]
the remaining absorb (for example Blood Shield) dont show on the player/target frame at full HP when SUI is activated
Edit: also not working with addon "DerangedShieldMeters"

**Comment by muleyo** [comment]
Fixed with the latest update.

**Comment by fanhubx** [comment]
still doesnt work for me
without SUI:
![WoWScrnShot_112622_132801](https://user-images.githubusercontent.com/119081405/204089381-cf5ba4d7-4ded-4c05-9b90-dc14e9f00965.jpg)
with SUI
![WoWScrnShot_112622_132640](https://user-images.githubusercontent.com/119081405/204089402-9c0e7acc-dd1e-4d7e-b452-7a2fcfd764a3.jpg)
